sudo: required
services: 
 - docker
 
before_install:
 - docker build -t karthikganduri07/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true karthikganduri07/react-test npm run test
 
after_success:
 - docker build -t karthikganduri07/multi-client ./client
 - docker build -t karthikganduri07/multi-nginx ./nginx
 - docker build -t karthikganduri07/multi-server ./server
 - docker build -t karthikganduri07/multi-worker ./worker
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 #Push images to docker hub
 - docker push karthikganduri07/multi-client
 - docker push karthikganduri07/multi-nginx
 - docker push karthikganduri07/multi-server
 - docker push karthikganduri07/multi-worker
