sudo: required
services: 
 - docker
 
before_install:
 - docker build -t karthikganduri/react-test -f ./client/Dockerfile.dev .

script:
 - docker run karthikganduri/react-test npm run test -- --coverage
 
after_success:
 - docker build -t karthikganduri/multi-client ./client
 - docker build -t karthikganduri/multi-nginx ./nginx
 - docker build -t karthikganduri/multi-server ./server
 - docker build -t karthikganduri/multi-worker ./worker
 
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 #Push images to docker hub
 - docker push karthikganduri/multi-client
 - docker push karthikganduri/multi-nginx
 - docker push karthikganduri/multi-server
 - docker push karthikganduri/multi-worker
